USE blog;
ALTER TABLE user ADD COLUMN github_id VARCHAR(50) DEFAULT NULL AFTER role;
ALTER TABLE user ADD COLUMN gitee_id VARCHAR(50) DEFAULT NULL AFTER github_id;
ALTER TABLE user ADD COLUMN source VARCHAR(20) DEFAULT 'local' AFTER gitee_id;
